name: Build zip files and deploy them to the repo.

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Zip artifact for deployment
        run: |
            mkdir -p ./.bin
            for dir in */; do
              [ -d "$dir" ] || continue
              zip -r "./.bin/${dir%/}.zip" "$dir"
            done

      - name: Setup Git
        env: 
          GITHUB_ACTOR: ${{ github.actor }} 
        run: |
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            
      - name: Remove old zip files (pub branch)
        continue-on-error: true
        run: |
            git push origin -q -d "pub"

      - name: Generate pub branch with new zip files
        run: |
            git checkout -b "pub"
            git add ".bin"
            git commit -am "[bot] Automatically generated /.bin/*.zip files."
            git push origin "pub"
